#!/bin/bash
# Tool to do a simple public IP lookup using duckduckgo
# Requires: xmllint

# Query IP from duckduckgo
url="https://duckduckgo.com/?q=what+is+my+ip&t=canonical&ia=answer"
html=$(curl --max-time 5 -L "${url}" 2>/dev/null)

# The IP result will be in the html/body/script section
#   - extract the text
script_section=$(echo ${html} | xmllint --html --xpath "//html/body/script/text()" - 2>/dev/null)

# The answer will have the following form: 'Your IP address in XXX in <a herf=...>XXX"
echo $script_section | sed -r 's/.*"Your IP address is ([0-9\.]*) in <a.*>([^"]*)".*/\1\n\2/'

